# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90f0302395495cf5456d428e176ba6768088f5bcec8f996d2f0015a8145d28f61ee8a032f6d670f83f239363b91d0ee12b7addc95fae090363ca28b1e1a902a

test:
  secret_key_base: 6a21e508dc0fda3c6a1bab7ca2df87ff096df7f77866dd33d5adebd0113e16bc6042d1448ad4e7ebdd7492a54157fbfabc6907931653c50e7c2eed7edbeb1f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
